version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratelimiter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  garnet:
    image: ghcr.io/microsoft/garnet:latest
    ports:
      - "6379:6379"
    volumes:
      - garnet_data:/data
    command: ["--port", "6379"]

volumes:
  postgres_data:
  garnet_data: